<template>
  <Card :valkyrie="valkyrie" :signets="signets" />
</template>

<script setup>
import Card from "../../components/Card.vue";

const valkyrie = {
  id: "b438da93-3a90-487a-bf92-bb3b0c38c4f8",
  name: "Herrscher of Flamescion",
  imageSrc: "/images/herrscher-of-flamescion.png",
  imageAlt: "Herrscher of Flamescion",
  position: "object-center",
  derp: {
    imageSrc: "/images/derp/herrscher-of-flamescion.png",
    imageAlt: "Derp Herrscher of Flamescion",
    position: "object-center",
  }
};

const signets = {
  builds: [
    {
      name: "Recommendation",
      recommended: "Choose HoD",
      patch: "",
      boss: "Mobius",
      supports: [
        {
          time: "Early",
          sigils: "Mad King's Mask",
          support_1: "AE",
          support_2: "BR",
        },
        {
          time: "Mid",
          sigils: "Memory / Because of You (5F)",
          support_1: "AE",
          support_2: "BR",
        },
        {
          time: "Late",
          sigils: "Stained Sakura / Home Lost",
          support_1: "AE",
          support_2: "BR",
        },
      ],
      signets: [
        {
          name: "Elysia",
          lists: [
            {
              name: "Blessing of Heatflow",
              desc: "Black holes generated by the Herrscher of Flamescion deal 75% bonus Fire DMG. Triggering Ultimate Evasion Skill creates an additional black hole",
              priority: "Start",
            },
            {
              name: "Blessing of Reburn",
              desc: "Triggering Ultimate Evasion Skill removes Overheat and clears Heat",
              priority: "1st",
            },
            {
              name: "Blessing of Tempered Warrior",
              desc: "Aerial Combo ATKs reduce Ultimate Evasion Skill CD by 9s",
              priority: "2nd",
            },
            {
              name: "Blessing of Starfire",
              desc: "When a black hole created by the Herrscher of Flamescion ends, a smaller black hole lasting 5s is generated to deal 300% ATK of Fire DMG per second. CD: 3s",
              priority: "Filler",
            },
            {
              name: "Blessing of Flamescion",
              desc: "For every black hole created by the Herrscher of Flamescion, Valkyrie restores 25 HP per second and deals 30% bonus Total DMG",
              priority: "Filler",
            },
          ],
        },
        {
          name: "Elysia (low-gear)",
          lists: [
            {
              name: "Blessing of Heatflow",
              desc: "Black holes generated by the Herrscher of Flamescion deal 75% bonus Fire DMG. Triggering Ultimate Evasion Skill creates an additional black hole",
              priority: "Start",
            },
            {
              name: "Blessing of Starfire",
              desc: "When a black hole created by the Herrscher of Flamescion ends, a smaller black hole lasting 5s is generated to deal 300% ATK of Fire DMG per second. CD: 3s",
              priority: "1st",
            },
            {
              name: "Blessing of Reburn",
              desc: "Triggering Ultimate Evasion Skill removes Overheat and clears Heat",
              priority: "2nd",
            },
            {
              name: "Blessing of Tempered Warrior",
              desc: "Aerial Combo ATKs reduce Ultimate Evasion Skill CD by 9s",
              priority: "3rd",
            },
            {
              name: "Blessing of Flamescion",
              desc: "For every black hole created by the Herrscher of Flamescion, Valkyrie restores 25 HP per second and deals 30% bonus Total DMG",
              priority: "Filler",
            },
          ],
        },
        {
          name: "Kalpas 2",
          lists: [
            {
              name: "Bone, Blood, and Ribbon",
              desc: "Every 100 HP loss boosts Physical & Elemental DMG by 0.8%",
              priority: "1st",
            },
            {
              name: "Desireless, Mindless, and Homeless",
              desc: "Losing HP boosts Total DMG taken by all enemies by 25% for 8s",
              priority: "2nd",
            },
            {
              name: "Path, Misfortune, and Written Fate",
              desc: "Max HP increases by 25%",
              priority: "3rd",
            },
            {
              name: "Blade, Grave, and Scar",
              desc: "Every 100 HP loss boosts Total DMG by 1%",
              priority: "4th",
            },
            {
              name: "Nexus Signet: Soldiers, Scissors, Spoils, and Slaughter",
              desc: "Valkyrie's current HP cannot exceed 18% of her Max HP, and if the HP recovery in combat reaches 0/400/800, the recovery amount increases by of the Bloodboil Armor charges, up to for a single charge. The charge cap is 1800, and each point increases the HP cap by 1",
              priority: "CORE",
            },
            {
              name: "Hometown, Homeland, Friends, and Acquaintances",
              desc: "If [Bloodboil Garment] exceeds 1500, gain 25% physical and elemental breach",
              priority: "YES",
            },
            {
              name: "Death, Life, Oblivion, and Existence",
              desc: "The Bloodboil Armor charges cap increases by 500. At over 1500 charges, Bloodboil Armor can absorb DMG equal to 1% of its charges",
              priority: "Filler",
            },
          ],
        },
        {
          name: "Sakura 1",
          lists: [
            {
              name: "Bountiful Blossom: Koyo",
              desc: "Triggering Ultimate Evasion Skill boosts Total DMG taken by all enemies by 30% for 8s",
              priority: "1st",
            },
            {
              name: "Bountiful Blossom: Fuji",
              desc: "Ultimate Evasion Skill has 1 more charge and 10% reduced CD",
              priority: "2nd",
            },
            {
              name: "Bountiful Blossom: Ayame",
              desc: "Triggering Ultimate Evasion Skill restores 12.0 bonus SP",
              priority: "3rd",
            },
            {
              name: "Nexus Signet: Setsuna Blade: Sakura-ni-Maku",
              desc: "Triggering Ultimate Evasion Skill 3 times activates Sakura Screen to render all enemies static for 3s, after which they lose HP equal to 40% of the DMG they have received during the duration",
              priority: "CORE",
            },
            {
              name: "Setsuna Blade: Ino-Shika-Cho",
              desc: "When Sakura Screen is active, moving around can pause its duration countdown for up to 3.0s.",
              priority: "Filler",
            },
          ],
        },
        {
          name: "Su 2",
          lists: [
            {
              name: "Motto of Dibba-Cakkhu",
              desc: "Combo hits are reset at to boost Total DMG taken by all enemies by 35% for 10s",
              priority: "1st",
            },
            {
              name: "Motto of Asavakkhaya",
              desc: "Attacks grant 25 bonus combo hits on hit. CD: 5s",
              priority: "2nd",
            },
            {
              name: "Motto of Iddhi-Vidha",
              desc: "Combo hits are increased to 60 when below 60. CD: 10s",
              priority: "3rd",
            },
            {
              name: "Nexus Signet: Dictum of Bodhi",
              desc: "Reaching 60/100/150 combo hits unleashes Bodhi: Eyes Open on a random enemy, dealing 800%/900%/1000% ATK of adaptive DMG and inflicting Trance. Affected enemies contribute 1 bonus combo hit on hit for 3s",
              priority: "CORE",
            },
            {
              name: "Dictum of Santam",
              desc: "Bodhi: Eyes Open inflicts 3 random debuffs lasting 3s on hit.",
              priority: "1st",
            },
            {
              name: "Dictum of Anatman",
              desc: "The Bodhi: Eyes Open lasts for 3s longer. For every debuff on the target enemy, it takes 5% bonus Total DMG",
              priority: "2nd",
            },
          ],
        },
        {
          name: "Hua 2 (Optional, one or none)",
          lists: [
            {
              name: "Old Dreams Again",
              desc: "Elemental Breach increases by 0.6% per second",
              priority: "1st",
            },
            {
              name: "Dark Garb No More",
              desc: "Elemental DMG increases by 0.8% per second",
              priority: "2nd",
            },
            {
              name: "Long Trip",
              desc: "Total DMG increases by 1.0% per second. 40 stacks max. Taking DMG reduces 10 stacks",
              priority: "3rd",
            },
            {
              name: "Nexus Signet: Suffering Mass",
              desc: "Valkyries start with 6 Soldier's Remembrance stacks which boost all buffs from Normal Signets of Vicissitude to full stacks. Taking DMG reduces I Soldier's Remembrance stack and grants 0.5s invincibility",
              priority: "CORE",
            },
            {
              name: "Broken Dream",
              desc: "With Soldier's Remembrance stacks, the max stacks of all buffs from Normal Signets of Vicissitude increase by 20. Losing all Soldier's Remembrance stacks reduces the max stacks by 10 but restores 1 Soldier's Remembrance stack. Can only be triggered once every battle",
              priority: "YES",
            },
          ],
        },
        {
          name: "Eden 1 (Optional, one or none)",
          lists: [
            {
              name: "Recitatif of Creeks",
              desc: "Every 10 SP left boosts Physical & Elemental DMG by 2.5%",
              priority: "1st",
            },
            {
              name: "Recitatif of Eden",
              desc: "Every 10 SP left boosts Total DMG by 3.0%",
              priority: "2nd",
            },
            {
              name: "Recitatif of Good Wine",
              desc: "Restore 1.5 SP per second",
              priority: "3rd",
            },
            {
              name: "Nexus Signet: Aria of Gold",
              desc: "Restoring 100 SP in total triggers 3 Lightning of Aria bolts each dealing 450% ATK of Lightning DMG and inflicting 6s of Intoxicate randomly. Intoxicated enemies take 15% bonus Total DMG",
              priority: "CORE",
            },
          ],
        },
        {
          name: "Eden 2 (Optional, one or none)",
          lists: [
            {
              name: "Recitatif of Creeks",
              desc: "Every 10 SP left boosts Physical & Elemental DMG by 2.5%",
              priority: "1st",
            },
            {
              name: "Recitatif of Eden",
              desc: "Every 10 SP left boosts Total DMG by 3.0%",
              priority: "2nd",
            },
            {
              name: "Recitatif of Good Wine",
              desc: "Restore 1.5 SP per second",
              priority: "3rd",
            },
            {
              name: "Nexus Signet: Echo of Gold",
              desc: "Consuming SP restores the same charges and triggers Final Echo status during which Total DMG increases 8% (160% max) at the cost of charges equal to the remaining duration per second. Insufficient charges reset the effect and end Final Echo",
              priority: "CORE",
            },
            {
              name: "Echo of Silent Night",
              desc: "After lasting over 7s, reduce ATK, DEF, ele resists of enemies nearby",
              priority: "1st",
            },
            {
              name: "Echo of Withered Soil",
              desc: "After lasting over 7s, boost SP cap and restore SP/s till it ends",
              priority: "Filler",
            },
          ],
        },
        {
          name: "Griseo 1 (Optional, one or none)",
          lists: [
            {
              name: "Red & Hot",
              desc: "Using a weapon active taints enemies nearby with red paint for 8s and makes them take 25% bonus Physical and Elemental MG (cannot stack). Triggering it again resets the duration",
              priority: "1st",
            },
            {
              name: "Yellow & Warm",
              desc: "Using an Ultimate taints enemies nearby with yellow paint for 8s and makes them take 30% bonus Total DMG. Triggering it again resets the duration",
              priority: "2nd",
            },
            {
              name: "Grey & Empty",
              desc: "Enemies stay tainted for 5s longer",
              priority: "3rd",
            },
            {
              name: "Nexus Signet: Shine like Stars",
              desc: "When there are enemies tainted with 1/2/3 different paints, Valkyries deal 20%/50%/100% bonus Total DMG to enemies of countering types",
              priority: "CORE",
            },
            {
              name: "Burning Like Flames",
              desc: "When enemies are tainted with both yellow and red paints, Valkyries have 25% bonus Physical and Elemental Breach against them.",
              priority: "1st (if no breach, otherwise Filler)",
            },
          ],
        },
      ],
    },
  ],
};
</script>
